# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
absl-py=2.0.0=pypi_0
aiofiles=22.1.0=py311haa95532_0
aiosqlite=0.18.0=py311haa95532_0
anyio=3.5.0=py311haa95532_0
argon2-cffi=21.3.0=pyhd3eb1b0_0
argon2-cffi-bindings=21.2.0=py311h2bbff1b_0
asttokens=2.0.5=pyhd3eb1b0_0
astunparse=1.6.3=pypi_0
attrs=23.1.0=py311haa95532_0
babel=2.11.0=py311haa95532_0
backcall=0.2.0=pyhd3eb1b0_0
beautifulsoup4=4.12.2=py311haa95532_0
blas=1.0=mkl
bleach=4.1.0=pyhd3eb1b0_0
brotlipy=0.7.0=py311h2bbff1b_1002
bzip2=1.0.8=he774522_0
ca-certificates=2023.08.22=haa95532_0
cachetools=5.3.1=pypi_0
certifi=2023.7.22=py311haa95532_0
cffi=1.15.1=py311h2bbff1b_3
chardet=5.2.0=pypi_0
charset-normalizer=3.3.0=pypi_0
colorama=0.4.6=py311haa95532_0
comm=0.1.2=py311haa95532_0
contourpy=1.1.1=pypi_0
cryptography=41.0.3=py311h89fc84f_0
cuda=12.3.0=0
cuda-cccl=12.3.52=0
cuda-command-line-tools=12.3.0=0
cuda-compiler=12.3.0=0
cuda-cudart=12.3.52=0
cuda-cudart-dev=12.3.52=0
cuda-cuobjdump=12.3.52=0
cuda-cupti=12.3.52=0
cuda-cuxxfilt=12.3.52=0
cuda-demo-suite=12.3.52=0
cuda-documentation=12.3.52=0
cuda-libraries=12.3.0=0
cuda-libraries-dev=12.3.0=0
cuda-nsight-compute=12.3.0=0
cuda-nvcc=12.3.52=0
cuda-nvdisasm=12.3.52=0
cuda-nvml-dev=12.3.52=0
cuda-nvprof=12.3.52=0
cuda-nvprune=12.3.52=0
cuda-nvrtc=12.3.52=0
cuda-nvrtc-dev=12.3.52=0
cuda-nvtx=12.3.52=0
cuda-nvvp=12.3.52=0
cuda-opencl=12.3.52=0
cuda-opencl-dev=12.3.52=0
cuda-profiler-api=12.3.52=0
cuda-runtime=12.3.0=0
cuda-sanitizer-api=12.3.52=0
cuda-toolkit=12.3.0=0
cuda-tools=12.3.0=0
cuda-visual-tools=12.3.0=0
cycler=0.12.1=pypi_0
debugpy=1.6.7=py311hd77b12b_0
decorator=5.1.1=pyhd3eb1b0_0
defusedxml=0.7.1=pyhd3eb1b0_0
entrypoints=0.4=py311haa95532_0
executing=0.8.3=pyhd3eb1b0_0
flatbuffers=23.5.26=pypi_0
fonttools=4.43.1=pypi_0
gast=0.5.4=pypi_0
google-auth=2.23.3=pypi_0
google-auth-oauthlib=1.0.0=pypi_0
google-pasta=0.2.0=pypi_0
grpcio=1.59.0=pypi_0
h5py=3.10.0=pypi_0
idna=3.4=py311haa95532_0
intel-openmp=2023.1.0=h59b6b97_46319
ipykernel=6.25.0=py311h746a85d_0
ipython=8.15.0=py311haa95532_0
ipython_genutils=0.2.0=pyhd3eb1b0_1
jedi=0.18.1=py311haa95532_1
jinja2=3.1.2=py311haa95532_0
joblib=1.3.2=pypi_0
json5=0.9.6=pyhd3eb1b0_0
jsonschema=4.17.3=py311haa95532_0
jupyter_client=7.4.9=py311haa95532_0
jupyter_core=5.3.0=py311haa95532_0
jupyter_events=0.6.3=py311haa95532_0
jupyter_server=1.23.4=py311haa95532_0
jupyter_server_fileid=0.9.0=py311haa95532_0
jupyter_server_ydoc=0.8.0=py311haa95532_1
jupyter_ydoc=0.2.4=py311haa95532_0
jupyterlab=3.6.3=py311haa95532_0
jupyterlab_pygments=0.1.2=py_0
jupyterlab_server=2.22.0=py311haa95532_0
keras=2.14.0=pypi_0
keras-preprocessing=1.1.2=pypi_0
keras-self-attention=0.51.0=pypi_0
kiwisolver=1.4.5=pypi_0
libclang=16.0.6=pypi_0
libcublas=12.3.2.9=0
libcublas-dev=12.3.2.9=0
libcufft=11.0.11.19=0
libcufft-dev=11.0.11.19=0
libcurand=10.3.4.52=0
libcurand-dev=10.3.4.52=0
libcusolver=11.5.3.52=0
libcusolver-dev=11.5.3.52=0
libcusparse=12.1.3.153=0
libcusparse-dev=12.1.3.153=0
libffi=3.4.4=hd77b12b_0
libiconv=1.16=h2bbff1b_2
libnpp=12.2.2.32=0
libnpp-dev=12.2.2.32=0
libnvjitlink=12.3.52=0
libnvjitlink-dev=12.3.52=0
libnvjpeg=12.2.3.32=0
libnvjpeg-dev=12.2.3.32=0
libsodium=1.0.18=h62dcd97_0
libxml2=2.10.4=h0ad7f3c_1
libxslt=1.1.37=h2bbff1b_1
lxml=4.9.3=py311h09808a7_0
markdown=3.5=pypi_0
markupsafe=2.1.3=pypi_0
matplotlib=3.8.0=pypi_0
matplotlib-inline=0.1.6=py311haa95532_0
mistune=0.8.4=py311h2bbff1b_1000
mkl=2023.1.0=h6b88ed4_46357
mkl-service=2.4.0=py311h2bbff1b_1
mkl_fft=1.3.8=py311h2bbff1b_0
mkl_random=1.2.4=py311h59b6b97_0
ml-dtypes=0.2.0=pypi_0
nbclassic=0.5.5=py311haa95532_0
nbclient=0.5.13=py311haa95532_0
nbconvert=6.5.4=py311haa95532_0
nbformat=5.9.2=py311haa95532_0
nest-asyncio=1.5.6=py311haa95532_0
notebook=6.5.4=py311haa95532_1
notebook-shim=0.2.2=py311haa95532_0
nsight-compute=2023.3.0.12=0
numpy=1.26.1=pypi_0
oauthlib=3.2.2=pypi_0
openssl=3.0.12=h2bbff1b_0
opt-einsum=3.3.0=pypi_0
packaging=23.2=pypi_0
pandas=2.1.1=pypi_0
pandocfilters=1.5.0=pyhd3eb1b0_0
parso=0.8.3=pyhd3eb1b0_0
pickleshare=0.7.5=pyhd3eb1b0_1003
pillow=10.1.0=pypi_0
pip=23.2.1=py311haa95532_0
platformdirs=3.10.0=py311haa95532_0
prometheus_client=0.14.1=py311haa95532_0
prompt-toolkit=3.0.36=py311haa95532_0
protobuf=4.24.4=pypi_0
psutil=5.9.0=py311h2bbff1b_0
pure_eval=0.2.2=pyhd3eb1b0_0
pyasn1=0.5.0=pypi_0
pyasn1-modules=0.3.0=pypi_0
pycparser=2.21=pyhd3eb1b0_0
pygments=2.15.1=py311haa95532_1
pyopenssl=23.2.0=py311haa95532_0
pyparsing=3.1.1=pypi_0
pyrsistent=0.18.0=py311h2bbff1b_0
pysocks=1.7.1=py311haa95532_0
python=3.11.5=he1021f5_0
python-dateutil=2.8.2=pyhd3eb1b0_0
python-fastjsonschema=2.16.2=py311haa95532_0
python-json-logger=2.0.7=py311haa95532_0
pytz=2023.3.post1=py311haa95532_0
pywin32=305=py311h2bbff1b_0
pywinpty=2.0.10=py311h5da7b33_0
pyyaml=6.0=py311h2bbff1b_1
pyzmq=23.2.0=py311hd77b12b_0
requests=2.31.0=py311haa95532_0
requests-oauthlib=1.3.1=pypi_0
rfc3339-validator=0.1.4=py311haa95532_0
rfc3986-validator=0.1.1=py311haa95532_0
rsa=4.9=pypi_0
scikit-learn=1.3.1=pypi_0
scipy=1.11.3=pypi_0
seaborn=0.13.0=pypi_0
send2trash=1.8.0=pyhd3eb1b0_1
setuptools=68.0.0=py311haa95532_0
six=1.16.0=pyhd3eb1b0_1
sniffio=1.2.0=py311haa95532_1
soupsieve=2.5=py311haa95532_0
sqlite=3.41.2=h2bbff1b_0
stack_data=0.2.0=pyhd3eb1b0_0
tbb=2021.8.0=h59b6b97_0
tensorboard=2.14.1=pypi_0
tensorboard-data-server=0.7.1=pypi_0
tensorflow=2.14.0=pypi_0
tensorflow-estimator=2.14.0=pypi_0
tensorflow-intel=2.14.0=pypi_0
tensorflow-io-gcs-filesystem=0.31.0=pypi_0
termcolor=2.3.0=pypi_0
terminado=0.17.1=py311haa95532_0
threadpoolctl=3.2.0=pypi_0
tinycss2=1.2.1=py311haa95532_0
tk=8.6.12=h2bbff1b_0
tornado=6.3.3=py311h2bbff1b_0
traitlets=5.7.1=py311haa95532_0
typing-extensions=4.8.0=pypi_0
typing_extensions=4.7.1=py311haa95532_0
tzdata=2023.3=pypi_0
urllib3=2.0.6=pypi_0
vc=14.2=h21ff451_1
vs2015_runtime=14.27.29016=h5e58377_2
wcwidth=0.2.5=pyhd3eb1b0_0
webencodings=0.5.1=py311haa95532_1
websocket-client=0.58.0=py311haa95532_4
werkzeug=3.0.0=pypi_0
wheel=0.41.3=pypi_0
win_inet_pton=1.1.0=py311haa95532_0
winpty=0.4.3=4
wrapt=1.14.1=pypi_0
xz=5.4.2=h8cc25b3_0
y-py=0.5.9=py311hb6bf4ef_0
yaml=0.2.5=he774522_0
ypy-websocket=0.8.2=py311haa95532_0
zeromq=4.3.4=hd77b12b_0
zlib=1.2.13=h8cc25b3_0
